### ISSUE TITLE
Q: Web UI and Response description

### ISSUE THREAD

**Issue by casudo** [simonsagstetter/kickbase-api-v4-docs#1]
Hi! First of all, I don't know if @kevinskyba has planned to update his 4 year old Kickbase API docs, but my suggestions is that we or you setup a web GUI to browse through all of the endpoints. I think that would be easier for many people instead of importing the Postman collection.

I would be happy to contribute by adding a comment to what the response parameters actually mean. :-)

LMK what you think.

**Comment by simonsagstetter** [comment]
Yes a browseable GUI is a good approach to make this documentation easy and accessible. For those who really want to dive deep into the api endpoints a postman collection is maybe the better choice, because you can test endpoints right away.

Like I wrote in the description this is a really quick and dirty way to provide my information about the endpoints asap to the community as a lot of people are struggling getting their applications back up and running. 

@kevinskyba used [postmanerator](https://github.com/aubm/postmanerator) to create a html version of the postman collection. I will generate a web version and link it via github pages into the README. If you want to help me with the response bodies you could import the postman collection into your postman app, add descriptions and export it to update this repository. This way I can easily recreate and update the documentation when changes occur. 

Or is there an even easier way? What do you think?

**Comment by simonsagstetter** [comment]
> Seems like the fastest way. I haven't used postmanerator yet, are saved responses aka the comments in it also displayed in the GUI?

I don't know yet. I'll test it with my collection and give you feedback.

**Comment by casudo** [comment]
> > Seems like the fastest way. I haven't used postmanerator yet, are saved responses aka the comments in it also displayed in the GUI?
> 
> I don't know exactly. I think its the descriptions you can add inside the collection documentation of postman. I'll test it with my collection and give you feedback.

I meant the "Save response" button in Postman.
You can save the whole response and add comments there.

![image](https://github.com/user-attachments/assets/c007701a-2cdd-4639-afeb-9f5d8d51b3eb)
![image](https://github.com/user-attachments/assets/c6170a7b-6264-4d22-a710-ddba56dcdbbe)

**Comment by simonsagstetter** [comment]
The saved responses are NOT appearing in the postman documentation collection but it could be that postmanerator can access them somehow and add them to the generated index.html. This is what I need to test first. Alternatively you can post script with postman and javascript but i've never done that before. So let me check first if postmanerator can do that for us.

**Comment by kevinskyba** [comment]
If you guys want I can give you the rights for the repo to update to v4 and make it nicer. I personally do not have much time currently.

**Comment by simonsagstetter** [comment]
> If you guys want I can give you the rights for the repo to update to v4 and make it nicer. I personally do not have much time currently.

@kevinskyba 
That would be nice. That way we could keep the docs  in a repository which is already well-kown int the community.

@casudo we will need another postman to html generator tool since postmanerator does not recognize more than one nested folder structure and somehow is the http request url sometimes pre-encoded. Although it can display saved responses in the generated html....

<img width="269" alt="image" src="https://github.com/user-attachments/assets/dfc0243e-4086-440b-b9a5-c98d47380013">
<img width="874" alt="image" src="https://github.com/user-attachments/assets/58f85547-6082-45a6-a692-30a6a200e1c4">

I found this tool [postman-doc-gen](https://github.com/karthiks3000/postman-doc-gen) which looks quite promising and I've already tested it. WDYT?

**Comment by kevinskyba** [comment]
Invites have been sent out.

**Comment by casudo** [comment]
> > If you guys want I can give you the rights for the repo to update to v4 and make it nicer. I personally do not have much time currently.
> 
> 
> 
> @kevinskyba 
> 
> That would be nice. That way we could keep the docs  in a repository which is already well-kown int the community.
> 
> 
> 
> @casudo we will need another postman to html generator tool since postmanerator does not recognize more than one nested folder structure and somehow is the http request url sometimes pre-encoded. Although it can display saved responses in the generated html....
> 
> 
> 
> <img width="269" alt="image" src="https://github.com/user-attachments/assets/dfc0243e-4086-440b-b9a5-c98d47380013">
> 
> <img width="874" alt="image" src="https://github.com/user-attachments/assets/58f85547-6082-45a6-a692-30a6a200e1c4">
> 
> 
> 
> I found this tool [postman-doc-gen](https://github.com/karthiks3000/postman-doc-gen) which looks quite promising and I've already tested it. WDYT?
> 
> 

Yep, also seen this in the wild once, could be good. What do you Think if we separate the Postman Collection from the Web UI with eg Swagger?

**Comment by simonsagstetter** [comment]
I've never worked with swagger and I have no experience with this tool. I think there is a way to [convert a postman collection to swagger json](https://www.postman.com/postman/postman-public-workspace/documentation/ijkf7ei/postman-to-swagger-oas-2) otherwise you would have to write the docs from scratch. 

I also updated my repository to test the [postman-doc-gen](https://github.com/karthiks3000/postman-doc-gen).
See [HERE](https://simonsagstetter.github.io/kickbase-api-v4-docs/)

**Comment by simonsagstetter** [comment]
So after a little bit of research and testing I was able to convert my postman collection to swagger.json with [this guide](https://www.postman.com/postman/postman-public-workspace/documentation/ijkf7ei/postman-to-swagger-oas-2). After importing to swagger hub I had to convert it to OAS3.0 to be able to edit all the request and response information and as I did that I noticed you need a active subscription to work on it long term. There is 14 day trial.

I found another guide from [Apidog](https://apidog.com/blog/export-postman-documentation-to-html-or-markdown/) where you can import a postman collection, convert it into swagger.json and export a swaggerUI html version which is free!

I think it would be the best idea to have a shared postman collection and use apidog for the export of the desired formats html, swagger.json eg. Is easy and pretty straight forward. You can check out the html version in my repository or try it out by yourself.

Let me know what you think! :)

**Comment by casudo** [comment]
This looks awesome and seems very easy to maintain. I would be happy with that solution. 💯
Thanks for testing it out!

**Comment by simonsagstetter** [comment]
Lets continue this discussion [HERE](https://github.com/kevinskyba/kickbase-api-doc/issues/4)
